##### Tidy clinical metadata. #####
# This script generates a merged table of diagnosis and treatment information 
# (generated by Henry Ngu) linked to biopsy ID and pathology from the 
# MTP_Internal_Overview database table. The output of this script will be 
# tidied up manually to remove extraneous 

source("src/libs.R")

trios_md <- read_tsv("data/metadata/metadata_sequencing.tsv")

mtp <- read_excel("../private_data/MTP_Internal_overview.xlsx")
mtp_path <- mtp %>% 
  select(patient_id = Patient_ID, 
         biopsy_id = Biopsy_ID, 
         DTBX,
         PATHa) %>% 
  filter(patient_id %in% trios_md$patient_id) %>% 
  left_join(select(trios_md, patient_id, biopsy_id, DNAseq_sample_id, pathology)) %>% 
  mutate(pathology = case_when(
    !is.na(pathology) ~ pathology, 
    str_detect(PATHa, "FOLL") ~ "FL", 
    PATHa == "DLBC" ~ "DLBCL",
    TRUE ~ PATHa
  ))  %>% 
  select(-PATHa)

clinical_md <- read_excel("../private_data/DLBCL_Trios_Clinical_HN290322.xlsx")
clinical_md_biopsy <- clinical_md %>% 
  select(patient_id = res_id, DIAG1, everything()) %>%
  filter(patient_id %in% trios_md$patient_id) %>%
  mutate(across(DTDX1:TX4, as.character)) %>% 
  pivot_longer(DTDX1:TX4, 
               names_to = "variable", 
               values_to = "value") %>% 
  extract(variable, into = c("variable", "timepoint"), regex = "(.+)([[:digit:]]{1})") %>% 
  pivot_wider(names_from = "variable", values_from = "value", id_cols = c("patient_id", "timepoint", "DIAG1")) %>% 
  rename(biopsy_id = Biopsy_ID) %>% 
  filter(patient_id %in% trios_md$patient_id) %>% 
  group_by(patient_id) %>% 
  ungroup() %>% 
  select(patient_id, biopsy_id, biopsy_site = Biopsy_site, timepoint, DIAG1, DTDX, DTBX, TX, `CT/PET`, NOTE) %>% 
  mutate(DTBX = as.Date(DTBX), 
         DTDX = as.Date(DTDX)) %>% 
  full_join(mtp_path) %>% 
  filter(!(is.na(DTBX) & is.na(DTDX))) %>% 
  group_by(patient_id, DTBX) %>% 
  summarize(across(everything(), ~ paste0(.x[!is.na(.x)], collapse = ", "))) %>% 
  ungroup() %>% 
  select(
    patient_id, 
    DTBX, 
    biopsy_id, 
    biopsy_site, 
    DIAG = DIAG1, 
    DTDX_pt = DTDX, 
    TX, 
    `CT/PET`, 
    sample_id = DNAseq_sample_id, 
    pathology
  ) %>% 
  mutate(across(matches("^DT"), as.Date))
  
clinical_md_current <- read_excel("../private_data/clinical_md_biopsy_FINAL.xlsx")

clinical_md_added <- bind_rows(clinical_md_current, filter(clinical_md_biopsy, !patient_id %in% clinical_md_current$patient_id))

write_tsv(clinical_md_added, "../private_data/clinical_md_biopsy_20221013.tsv")

write_tsv(clinical_md_biopsy, "../private_data/clinical_md_biopsy_tmp.tsv")  

# Downloaded this file locally and curated it to remove likely staging biopsies
# and clean up pathology column. 



# filter(!is.na(sample_id) | 
  #          str_detect(pathology, "COMFL|FL|DLBC|HGBL|MALT|MZL|NS[123]|SLL"))

clinical_md_pt <- clinical_md %>% 
  select(patient_id = res_id, 
         age = AGE, 
         sex = SEX, 
         DTDX = DTBX0, 
         DIAG = DIAG1,
         DTFUP, 
         CODE_OS, 
         OS_YEARS = `Overall survival (y)`, 
         CAUSE_DEATH,
         BMT, 
         DTBMT, 
         DTProgPostBMT) %>% 
  # mutate(DTFUP = as.POSIXct(as.Date(as.numeric(DTFUP), origin = "1899-12-30"), format="%Y-%m-%d")) %>% 
  mutate(DIAG = case_when(
    DIAG  == "DLBC" ~ "DLBCL", 
    str_detect(DIAG, "FOLL") ~ "FL", 
    DIAG == "COM" ~ "COMFL", 
    TRUE ~ DIAG
  )) %>% 
  filter(patient_id %in% clinical_md_biopsy$patient_id) %>% 
  distinct()

write_tsv(clinical_md_pt, "data/metadata/metadata_clinical_patient.tsv")

# Reload the curated biopsy metadata and join it with the patient data for sanity checking. 
clinical_md_biopsy_curated <- read_excel("../private_data/clinical_md_biopsy_curated.xlsx") 

write_tsv(
  select(clinical_md_biopsy_curated,-c(`Comment Laura`, DIAG1)),
  "data/metadata/metadata_clinical_biopsy.tsv"
)

clinical_md_biopsy_curated <- clinical_md_biopsy_curated %>% 
  rename(DTDX_bx = DTDX) %>% 
  left_join(clinical_md_pt, by = "patient_id") %>% 
  rename(DTDX_pt = DTDX) %>% 
  select(patient_id, DTDX_pt, any_of(colnames(clinical_md_pt)), biopsy_id, DTDX_bx, DTBX, any_of(colnames(clinical_md_biopsy_curated)))

write_tsv(clinical_md_biopsy_curated, "../private_data/clinical_md_biopsy_to_check.tsv")


missing_patients <- trios_md %>% 
  filter(!patient_id %in% clinical_md$res_id, 
         !str_detect(patient_id, "LY_RELY")) %>%
  pull(patient_id) %>% 
  unique()

# One patient 16-43741 is currently missing from the clinical metadata. 
# Will ask Henry to add it. 


